### PR TITLE
Add first batch of venues

### PR DESCRIPTION
**Pull request by orangejulius**
These are the first venue bundles ready for usage. Eventually, we will need a more flexible system than storing all venue bundles in an array (there are [hundreds of different repos with venue data](https://github.com/whosonfirst-data/whosonfirst-data-venue/blob/master/data.json), all of which will probably have their own bundles soon), but for now this is fine.

### CODE REVIEW

**Comment by trescube** [comment]
:shipit:

**Comment by dianashk** [comment]
LGTM Hooray!!!

**Comment by missinglink** [comment]
:shipit:

**Comment by missinglink** [comment]
waiting on one this that removed Texas

**Comment by orangejulius** [comment]
Okay, TX and UT (which have no bundles yet) have been removed. looking for one more LGTM :)

**Comment by orangejulius** [comment]
Or apparently i can do it myself...weird

**Pull request merged**
