### PR TITLE
incorporated `batchflow` module to download sequentially

### LINKED ISSUE #102: Maximum call stack size exceeded/Unhandled stream error in pipe while running npm run download
```
> node download_data.js

starting borough
starting continent
starting country
starting county
starting dependency
starting disputed
starting localadmin
starting locality
starting macrocounty
starting macroregion
starting neighbourhood
starting region
done borough
done disputed
done dependency
done macrocounty
done continent
done macroregion
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

RangeError: Maximum call stack size exceeded
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at onheader (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:122:12)
    at Extract._write (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:243:8)
    at Extract._continue (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:207:28)
    at oncontinue (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:64:10)
    at onunlock (/data/pelias-2/whosonfirst/node_modules/tar-stream/extract.js:70:24)
    at handleEntry (/data/pelias-2/whosonfirst/download_data.js:47:3)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)

npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "download"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! pelias-whosonfirst@1.0.0 download: `node download_data.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pelias-whosonfirst@1.0.0 download script 'node download_data.js'.
npm ERR! This is most likely a problem with the pelias-whosonfirst package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node download_data.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-whosonfirst
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pelias-whosonfirst
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/pelias-2/whosonfirst/npm-debug.log
```

### PR DESCRIPTION
**Pull request by trescube**
I performed a few tests and found that just downloading/untarring 1 bundle at a time is the fastest.

Fixes #102 (hopefully)

### CODE REVIEW

**Comment by orangejulius** [comment]
@easherma, can you test this branch?

**Comment by easherma** [comment]
@orangejulius I can if I get some spare time, but for my current build I already just imported from the cloned repo :-/

**Comment by orangejulius** [comment]
No worries, we will get it tested, but it would of course be nice to get outside confirmation that it improves things as well.

**Comment by orangejulius** [comment]
worked for me! :shipit:

**Comment by trescube** [comment]
The shame about this is that the `https.get`->`bz2`->`tar` node stream appears to be a significant bottleneck.  I experimented with the locality bundle to see what the performance difference is:

- downloading using `wget` and then running `tar -xjf`: 27s+1m38s=2m5s
- node streams: 6m19s

So it's 3x slower to use node streams than straight up `wget`/`tar`, but we're stuck with streams since we can't guarantee that someone isn't running this thing on windows with access to those utilities. 

On my laptop with node streams, the whole download takes 21m45.  Using `wget`/`tar` command line calls, it would take, presumably, 7m15s.

**Comment by trescube** [comment]
I've run this fix 3 times and haven't had any problems so I'm calling it fixed.

**Comment by orangejulius** [comment]
We can definitely write shell scripts that will work on Windows by the way. It's a bit of a pain, but with Cygwin it's been possible to use wget, tar, etc for a long time. Microsoft also recently announced an [emulation](http://www.pcworld.com/article/3094230/windows/oil-and-water-heres-ubuntu-linuxs-unity-desktop-running-natively-on-windows-10.html) layer that lets you run any Linux program on Windows.

**Comment by missinglink** [comment]
:shipit:

**Comment by missinglink** [comment]
would be nice to have something on the command line telling you that it's working, but not a biggie.

**Comment by kingcu** [comment]
Just a headsup, it doesn't appear this fixes #102 

err

**Comment by orangejulius** [comment]
Hey @kingcu,
Thanks for letting us know. What Node.js version are you running? In any case, we may be rewriting this to be faster and use more command line utilities to download and uncompress the data faster, so stay tuned.

**Comment by kingcu** [comment]
This was on node 6.4.0. I'm not too concerned with a resolution (though I am sure others are); after evaluating Pelias I decided to continue using Nominatim, despite its shortcomings. I'll be checking back in w/ the project in a year or so!

**Comment by dianashk** [comment]
Hey @kingcu, we'd love to hear more about your decision to continue using nominatim. What was the reason? What will you be looking for Pelias to support in a year or so when you check back in? This would help us to make our system better, so we'd really appreciate any feedback you could provide. 

Many thanks and best of luck with your project! 👋

**Comment by kingcu** [comment]
This isn't the place, but you can email me cullen@ridewithgps.com for details. I also sent an email to hello@mapzen.com earlier this week with some feedback.

**Pull request merged**
