### PR TITLE
Added continent to hierarchy in import

### PR DESCRIPTION
**Pull request by cag**
For this: https://github.com/pelias/pelias/issues/473

### CODE REVIEW

**Comment by orangejulius** [comment]
Hey @cag,
Can you edit the commit so that it doesn't include any changes to `package.json`? That helps keep things clean.

**Comment by cag** [comment]
Ah, I should have mentioned this. When I try to commit without adding tape, I get this:

```
$ git commit -am "Made the change without the package.json changes I accidentally included"
running lint...passed!
running validate...passed!
running test...failed!
module.js:474
    throw err;
    ^

Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alan/src/github.com/pelias/whosonfirst/test/components/extractFieldsTest.js:1:74)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

  



  

  0 tests
  0 passed
  0 failed  

  Failed Tests:   There were 0 failures
```

I suspect I just ran `npm install --save-dev tape` afterwards and committed it, which is what you see here. Here are my node and npm versions:

```
$ node -v
v7.1.0
$ npm -v
3.10.9
```

I am running Arch Linux.

Should I make another PR to address this?

**Comment by orangejulius** [comment]
No, there shouldn't be any PR needed. Tape is already specified in `package.json` Please try this:
1.) remove any changes to package.json compared to the master branch.
2.) From the whosonfirst repo directory, run `rm -rf node_modules/ && npm install` This will remove everything and reinstall it.  That should install tape.
3.) If that doesn't work, let us know. It might be because you're using Node.js 7. We don't yet officially support it, and probably won't for a little while.

**Comment by cag** [comment]
Oh yeah, you're right about tape already being in the devDependencies. In fact, I think it was installed. Sorry, I probably should have reported this separately. Here is what actually originally happened:

```
$ git commit -am "Made the change without the package.json changes I accidentally included"
running lint...passed!
running validate...failed!
pelias-whosonfirst@0.0.0-semantic-release /home/alan/src/github.com/pelias/whosonfirst
├── async@2.1.4
├─┬ combined-stream@1.0.5
│ └── delayed-stream@1.0.0
├── csv-parse@1.1.7
├─┬ event-stream@3.3.4
│ ├── duplexer@0.1.1
│ ├── from@0.1.3
│ ├── map-stream@0.1.0
│ ├── pause-stream@0.0.11
│ ├── split@0.3.3
│ ├── stream-combiner@0.0.4
│ └── through@2.3.8
├─┬ fs-extra@1.0.0
│ ├── graceful-fs@4.1.11
│ ├── jsonfile@2.4.0
│ └── klaw@1.3.1
├─┬ intercept-stdout@0.1.2
│ └─┬ lodash.toarray@3.0.2
│   ├── lodash._arraycopy@3.0.0
│   ├── lodash._basevalues@3.0.0
│   └─┬ lodash.keys@3.1.2
│     ├── lodash._getnative@3.9.1
│     ├── lodash.isarguments@3.1.0
│     └── lodash.isarray@3.0.4
├─┬ iso3166-1@0.2.8
│ └─┬ zlib-browserify@0.0.3
│   └── UNMET DEPENDENCY tape@~0.2.2
├─┬ jshint@2.9.4
│ ├── cli@1.0.1
│ ├─┬ console-browserify@1.1.0
│ │ └── date-now@0.1.4
│ ├── exit@0.1.2
│ ├─┬ htmlparser2@3.8.3
│ │ ├── domelementtype@1.3.0
│ │ ├── domhandler@2.3.0
│ │ ├─┬ domutils@1.5.1
│ │ │ └─┬ dom-serializer@0.1.0
│ │ │   ├── domelementtype@1.1.3
│ │ │   └── entities@1.1.1
│ │ ├── entities@1.0.0
│ │ └─┬ readable-stream@1.1.14
│ │   └── isarray@0.0.1
│ ├── lodash@3.7.0
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ ├── shelljs@0.3.0
│ └── strip-json-comments@1.0.4
├── lodash@4.17.2
├─┬ node-version-checker@2.0.0
│ ├── find-parent-dir@0.3.0
│ ├── semver@5.3.0
│ ├── shelljs@0.5.3
│ └─┬ yargs@3.32.0
│   ├── camelcase@2.1.1
│   ├─┬ cliui@3.2.0
│   │ └── wrap-ansi@2.1.0
│   ├── decamelize@1.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ └─┬ is-fullwidth-code-point@1.0.0
│   │   └── number-is-nan@1.0.1
│   ├── window-size@0.1.4
│   └── y18n@3.2.1
├─┬ pelias-config@2.3.1
│ └─┬ mergeable@0.0.0
│   └── extend@1.3.0
├─┬ pelias-dbclient@2.0.0
│ ├── byline@4.2.2
│ ├─┬ elasticsearch@11.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├── lodash@3.10.1
│ │ ├── lodash-compat@3.10.2
│ │ └─┬ promise@7.1.1
│ │   └── asap@2.0.5
│ ├─┬ openstreetmap-stream@0.1.0
│ │ ├─┬ osm-pbf-parser@2.1.2
│ │ │ └─┬ protocol-buffers@2.7.0
│ │ │   ├── protobuf-schema@1.5.1
│ │ │   ├── resolve-protobuf-schema@1.0.2
│ │ │   └── varint@4.0.1
│ │ ├─┬ stream-combiner2@1.0.2
│ │ │ ├── duplexer2@0.0.2
│ │ │ └─┬ through2@0.5.1
│ │ │   ├─┬ readable-stream@1.0.34
│ │ │   │ └── isarray@0.0.1
│ │ │   └── xtend@3.0.0
│ │ └─┬ through2@0.5.1
│ │   ├─┬ readable-stream@1.0.34
│ │   │ └── isarray@0.0.1
│ │   └── xtend@3.0.0
│ ├─┬ osm-pbf-parser@2.3.0
│ │ ├─┬ brfs@1.4.3
│ │ │ ├─┬ quote-stream@1.0.2
│ │ │ │ └── buffer-equal@0.0.1
│ │ │ └─┬ static-module@1.3.1
│ │ │   ├── concat-stream@1.4.10
│ │ │   ├─┬ escodegen@1.3.3
│ │ │   │ ├── esprima@1.1.1
│ │ │   │ ├── estraverse@1.5.1
│ │ │   │ ├── esutils@1.0.0
│ │ │   │ └─┬ source-map@0.1.43
│ │ │   │   └── amdefine@1.0.1
│ │ │   ├─┬ falafel@1.2.0
│ │ │   │ ├── acorn@1.2.2
│ │ │   │ └── isarray@0.0.1
│ │ │   ├── object-inspect@0.4.0
│ │ │   ├─┬ quote-stream@0.0.0
│ │ │   │ └── minimist@0.0.8
│ │ │   ├─┬ readable-stream@1.0.34
│ │ │   │ └── isarray@0.0.1
│ │ │   ├── shallow-copy@0.0.1
│ │ │   ├─┬ static-eval@0.2.4
│ │ │   │ └─┬ escodegen@0.0.28
│ │ │   │   ├── esprima@1.0.4
│ │ │   │   └── estraverse@1.3.2
│ │ │   └─┬ through2@0.4.2
│ │ │     └─┬ xtend@2.1.2
│ │ │       └── object-keys@0.4.0
│ │ ├─┬ protocol-buffers@3.2.1
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── protocol-buffers-schema@3.1.1
│ │ │ ├─┬ signed-varint@2.0.1
│ │ │ │ └── varint@5.0.0
│ │ │ └── varint@5.0.0
│ │ ├── readable-stream@2.2.2
│ │ └─┬ stream-combiner2@1.1.1
│ │   └── duplexer2@0.1.4
│ └── pelias-config@2.0.0
├─┬ pelias-logger@0.1.0
│ ├── pelias-config@2.3.0
│ └─┬ winston@2.3.0
│   ├── async@1.0.0
│   ├── colors@1.0.3
│   ├── cycle@1.0.3
│   ├── eyes@0.1.8
│   ├── isstream@0.1.2
│   └── stack-trace@0.0.9
├─┬ pelias-model@4.3.0
│ └── pelias-config@2.3.0
├── pelias-parallel-stream@0.0.2
├─┬ precommit-hook@3.0.0
│ └── git-validate@2.2.2
├─┬ semantic-release@6.3.2
│ ├── @bahmutov/parse-github-repo-url@0.1.2
│ ├─┬ @semantic-release/commit-analyzer@2.0.0
│ │ └─┬ conventional-changelog@0.0.17
│ │   ├─┬ dateformat@1.0.12
│ │   │ ├── get-stdin@4.0.1
│ │   │ └─┬ meow@3.7.0
│ │   │   ├── camelcase-keys@2.1.0
│ │   │   ├─┬ loud-rejection@1.6.0
│ │   │   │ └─┬ currently-unhandled@0.4.1
│ │   │   │   └── array-find-index@1.0.2
│ │   │   ├── map-obj@1.0.1
│ │   │   ├─┬ read-pkg-up@1.0.1
│ │   │   │ ├─┬ find-up@1.1.2
│ │   │   │ │ └── path-exists@2.1.0
│ │   │   │ └─┬ read-pkg@1.1.0
│ │   │   │   ├─┬ load-json-file@1.1.0
│ │   │   │   │ ├─┬ parse-json@2.2.0
│ │   │   │   │ │ └─┬ error-ex@1.3.0
│ │   │   │   │ │   └── is-arrayish@0.2.1
│ │   │   │   │ ├── pify@2.3.0
│ │   │   │   │ └─┬ strip-bom@2.0.0
│ │   │   │   │   └── is-utf8@0.2.1
│ │   │   │   └── path-type@1.1.0
│ │   │   ├─┬ redent@1.0.0
│ │   │   │ ├─┬ indent-string@2.1.0
│ │   │   │ │ └─┬ repeating@2.0.1
│ │   │   │ │   └── is-finite@1.0.2
│ │   │   │ └── strip-indent@1.0.1
│ │   │   └── trim-newlines@1.0.0
│ │   ├── lodash@3.10.1
│ │   └─┬ normalize-package-data@1.0.3
│ │     ├── github-url-from-username-repo@1.0.2
│ │     └── semver@4.3.6
│ ├─┬ @semantic-release/condition-travis@5.0.2
│ │ └─┬ travis-deploy-once@1.0.0-node-0.10-support
│ │   ├─┬ babel-polyfill@6.16.0
│ │   │ ├── babel-runtime@6.18.0
│ │   │ ├── core-js@2.4.1
│ │   │ └── regenerator-runtime@0.9.6
│ │   ├── bluebird@3.4.6
│ │   ├─┬ request@2.79.0
│ │   │ ├── aws-sign2@0.6.0
│ │   │ ├── aws4@1.5.0
│ │   │ ├── caseless@0.11.0
│ │   │ ├── extend@3.0.0
│ │   │ ├─┬ form-data@2.1.2
│ │   │ │ └── asynckit@0.4.0
│ │   │ ├─┬ har-validator@2.0.6
│ │   │ │ ├─┬ commander@2.9.0
│ │   │ │ │ └── graceful-readlink@1.0.1
│ │   │ │ ├─┬ is-my-json-valid@2.15.0
│ │   │ │ │ └── jsonpointer@4.0.0
│ │   │ │ └─┬ pinkie-promise@2.0.1
│ │   │ │   └── pinkie@2.0.4
│ │   │ ├─┬ hawk@3.1.3
│ │   │ │ ├── boom@2.10.1
│ │   │ │ ├── cryptiles@2.0.5
│ │   │ │ ├── hoek@2.16.3
│ │   │ │ └── sntp@1.0.9
│ │   │ ├─┬ http-signature@1.1.1
│ │   │ │ ├── assert-plus@0.2.0
│ │   │ │ ├─┬ jsprim@1.3.1
│ │   │ │ │ ├── extsprintf@1.0.2
│ │   │ │ │ ├── json-schema@0.2.3
│ │   │ │ │ └── verror@1.3.6
│ │   │ │ └─┬ sshpk@1.10.1
│ │   │ │   ├── asn1@0.2.3
│ │   │ │   ├── assert-plus@1.0.0
│ │   │ │   ├── bcrypt-pbkdf@1.0.0
│ │   │ │   ├─┬ dashdash@1.14.1
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├── ecc-jsbn@0.1.1
│ │   │ │   ├─┬ getpass@0.1.6
│ │   │ │   │ └── assert-plus@1.0.0
│ │   │ │   ├── jodid25519@1.0.2
│ │   │ │   ├── jsbn@0.1.0
│ │   │ │   └── tweetnacl@0.14.4
│ │   │ ├── is-typedarray@1.0.0
│ │   │ ├── json-stringify-safe@5.0.1
│ │   │ ├─┬ mime-types@2.1.13
│ │   │ │ └── mime-db@1.25.0
│ │   │ ├── oauth-sign@0.8.2
│ │   │ ├── qs@6.3.0
│ │   │ ├── stringstream@0.0.5
│ │   │ ├─┬ tough-cookie@2.3.2
│ │   │ │ └── punycode@1.4.1
│ │   │ ├── tunnel-agent@0.4.3
│ │   │ └── uuid@3.0.1
│ │   ├─┬ request-promise@4.1.1
│ │   │ ├── request-promise-core@1.1.1
│ │   │ └── stealthy-require@1.0.0
│ │   └─┬ travis-ci@2.1.1
│ │     ├── github@0.1.16
│ │     ├── lodash@1.3.1
│ │     ├─┬ request@2.74.0
│ │     │ ├─┬ bl@1.1.2
│ │     │ │ └── readable-stream@2.0.6
│ │     │ ├── extend@3.0.0
│ │     │ ├── form-data@1.0.1
│ │     │ ├── node-uuid@1.4.7
│ │     │ └── qs@6.2.1
│ │     └── underscore.string@2.2.1
│ ├── @semantic-release/error@1.0.0
│ ├─┬ @semantic-release/last-release-npm@1.2.1
│ │ ├─┬ npm-registry-client@7.4.1
│ │ │ ├─┬ concat-stream@1.5.2
│ │ │ │ ├── readable-stream@2.0.6
│ │ │ │ └── typedarray@0.0.6
│ │ │ ├── npm-package-arg@4.2.0
│ │ │ ├── retry@0.10.0
│ │ │ └── slide@1.1.6
│ │ └─┬ npmlog@1.2.1
│ │   ├── ansi@0.3.1
│ │   ├── are-we-there-yet@1.0.6
│ │   └─┬ gauge@1.2.7
│ │     ├── lodash.pad@4.5.1
│ │     ├── lodash.padend@4.6.1
│ │     └── lodash.padstart@4.6.1
│ ├─┬ @semantic-release/release-notes-generator@2.0.0
│ │ └── github-url-from-git@1.5.0
│ ├─┬ git-head@1.17.0
│ │ └─┬ git-refs@1.1.3
│ │   ├─┬ path-object@2.3.0
│ │   │ └─┬ lodash.assign@3.2.0
│ │   │   ├─┬ lodash._baseassign@3.2.0
│ │   │   │ └── lodash._basecopy@3.0.1
│ │   │   └─┬ lodash._createassigner@3.1.1
│ │   │     ├── lodash._bindcallback@3.0.1
│ │   │     ├── lodash._isiterateecall@3.0.9
│ │   │     └── lodash.restparam@3.6.1
│ │   ├── slash@1.0.0
│ │   └─┬ walk@2.3.9
│ │     └── foreachasync@3.0.0
│ ├─┬ github@0.2.4
│ │ └── mime@1.3.4
│ ├── nerf-dart@1.0.0
│ ├─┬ nopt@3.0.6
│ │ └── abbrev@1.0.9
│ ├─┬ normalize-package-data@2.3.5
│ │ ├── hosted-git-info@2.1.5
│ │ ├─┬ is-builtin-module@1.0.0
│ │ │ └── builtin-modules@1.1.1
│ │ └─┬ validate-npm-package-license@3.0.1
│ │   ├─┬ spdx-correct@1.0.2
│ │   │ └── spdx-license-ids@1.2.2
│ │   └── spdx-expression-parse@1.0.4
│ ├─┬ npmconf@2.1.2
│ │ ├─┬ config-chain@1.1.11
│ │ │ └── proto-list@1.2.4
│ │ ├── ini@1.3.4
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ ├─┬ once@1.3.3
│ │ │ └── wrappy@1.0.2
│ │ ├─┬ osenv@0.1.3
│ │ │ └── os-homedir@1.0.2
│ │ ├── semver@4.3.6
│ │ └── uid-number@0.0.5
│ ├─┬ npmlog@4.0.1
│ │ ├─┬ are-we-there-yet@1.1.2
│ │ │ └── delegates@1.0.0
│ │ ├── console-control-strings@1.1.0
│ │ ├─┬ gauge@2.7.2
│ │ │ ├── aproba@1.0.4
│ │ │ ├── has-unicode@2.0.1
│ │ │ ├── object-assign@4.1.0
│ │ │ ├── signal-exit@3.0.2
│ │ │ ├── supports-color@0.2.0
│ │ │ └── wide-align@1.1.0
│ │ └── set-blocking@2.0.0
│ ├── require-relative@0.8.7
│ ├─┬ run-auto@2.0.0
│ │ └── dezalgo@1.0.3
│ └── run-series@1.1.4
├─┬ tap-dot@1.0.5
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ └─┬ tap-out@1.4.2
│   ├── re-emitter@1.1.3
│   ├── readable-stream@2.2.2
│   ├── split@1.0.0
│   └── trim@0.0.1
├─┬ tape@4.6.3
│ ├── deep-equal@1.0.1
│ ├── defined@1.0.0
│ ├─┬ for-each@0.3.2
│ │ └── is-function@1.0.1
│ ├── function-bind@1.1.0
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├── inflight@1.0.6
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ ├── has@1.0.1
│ ├── inherits@2.0.3
│ ├── minimist@1.2.0
│ ├── object-inspect@1.2.1
│ ├── resolve@1.1.7
│ ├── resumer@0.0.0
│ └─┬ string.prototype.trim@1.1.2
│   ├─┬ define-properties@1.1.2
│   │ ├── foreach@2.0.5
│   │ └── object-keys@1.0.11
│   └─┬ es-abstract@1.6.1
│     ├─┬ es-to-primitive@1.1.1
│     │ ├── is-date-object@1.0.1
│     │ └── is-symbol@1.0.1
│     ├── is-callable@1.1.3
│     └── is-regex@1.0.3
├─┬ temp@0.8.3
│ ├── os-tmpdir@1.0.2
│ └── rimraf@2.2.8
├─┬ through2@2.0.3
│ ├─┬ readable-stream@2.2.2
│ │ ├── buffer-shims@1.0.0
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@1.0.0
│ │ ├── process-nextick-args@1.0.7
│ │ ├── string_decoder@0.10.31
│ │ └── util-deprecate@1.0.2
│ └── xtend@4.0.1
├── through2-filter@2.0.0
├── through2-map@3.0.0
├─┬ through2-sink@1.0.0
│ ├─┬ through2@0.5.1
│ │ └─┬ readable-stream@1.0.34
│ │   └── isarray@0.0.1
│ └── xtend@3.0.0
└── through2-spy@2.0.0

npm ERR! missing: tape@~0.2.2, required by zlib-browserify@0.0.3
```

Totally opaque to me, and I am not sure why updating tape caused it to work.

Just for reference, here is what I did afterwards to commit this:

```
$ npm install tape
pelias-whosonfirst@0.0.0-semantic-release /home/alan/src/github.com/pelias/whosonfirst
├─┬ iso3166-1@0.2.8
│ └─┬ zlib-browserify@0.0.3
│   └─┬ tape@0.2.2 
│     ├── deep-equal@0.0.0 
│     ├── defined@0.0.0 
│     └── jsonify@0.0.0 
└── tape@4.6.3 
```
The two `tape` entries are highlighted in my console, which tells me that they weren't included from the original `npm install`. Very strange.

**Comment by orangejulius** [comment]
Ah, yeah, this sort of problem happens with NPM all the time. Sometimes you have to run `npm install` twice. I think it's technically either bugs in NPM, or issues when handling very old versions of libraries, as is happening here. In that case the fix is to somehow get rid of those really old deps, which could be a pain considering how far the dependency chain things go.

**Comment by orangejulius** [comment]
Oh also, now that you know about `git rebase` (which we love <3), can you use it to combine these 3 commits (it should just have the commit message of the first one). Let me know if you need some help with it.

**Comment by cag** [comment]
Here ya go. Just realized hierarchy is spelled wrong but I'm not rebasing for that :P

**Comment by orangejulius** [comment]
Oh come on, it took you longer to say you weren't going to do it than to do it :P

**Comment by cag** [comment]
Oh, I mean that it's rebased, but I didn't catch my spelling mistake in time. Next time I'll just play it cool :P

Anyway, thanks for being patient with me. This has been one cumbersome line of code.

**Comment by orangejulius** [comment]
Hey @cag.
Sorry to leave you hanging on this for so long. We talked about this a while ago and at this point we aren't ready to tackle continents for a couple reasons:

1. We don't know how to handle the case of the many countries that are in two continents
2. Our current admin lookup architecture gets slower for every new layer of lookups we add: it doesn't matter if it has 100k+ entries like locality/localadmin, or only 6-8 like continent

We have plans to solve both of those problems in the future, so we'll revisit this when that happens.

**Pull request closed without merging**
