### PR TITLE
Switch to meta for files

### LINKED ISSUE #6: Read list of WOF data files via the meta files
This will considerably speed up the import since walking the WOF data directory is very slow in node

### PR DESCRIPTION
**Pull request by stephenkhess**
Modified readStream to use WOF meta files instead of walking directory
Switched importStream to retrieve parent information by walking parent_id instead of hierarchy fields 

Fixes #6

### CODE REVIEW

**Comment by riordan** [comment]
Just out of curiosity, what kind of performance improvement are you seeing?

**Comment by stephenkhess** [comment]
Not sure, I don't remember how long it took before.  I'll ask Julian on Tuesday.

**Comment by stephenkhess** [comment]
Just ran the current master code and it clocked in 8:48, so this change represents a doubling in performance.

**Comment by dianashk** [comment]
Awesome!

**Comment by orangejulius** [comment]
:+1:

**Pull request merged**
