### PR TITLE
Add borough support

### LINKED ISSUE #63: add `borough` place type support
Now that WOF has added support for NYC boroughs, we need to import them.

### PR DESCRIPTION
**Pull request by trescube**
Fixed #63

### CODE REVIEW

**Comment by orangejulius** [comment]
So does this include #62 ?

**Comment by trescube** [comment]
I branched from #62

**Comment by orangejulius** [comment]
Cool. How about we merge 62 after the last couple changes that I mentioned, then this will show just the actual changes needed for borough in the diff?

**Comment by trescube** [comment]
Sounds good

**Pull request merged**
