### PR TITLE
Download sqlite default endpoint to geocode.earth and remove bundle support

### LINKED ISSUE #437: download only whosonfirst-data-latest.db
Hi there,
I'm working currently on infrastructure for pip-service and it requires sqlite dump to be downloaded first. It turns out that this module downloads more than 150 dbs from dist.whosonfirst, even though later during pip-service start only 1 main file `whosonfirst-data-latest.db` is used. Is there a way to download only 1 file contains all data and not all of them?

ref: https://github.com/pelias/wof-admin-lookup/blob/master/src/pip/readStream.js#L21

### LINKED ISSUE #460: Default `whosonfirst.sqlite` to true
We have been testing the SQLite download option introduced in https://github.com/pelias/whosonfirst/pull/417 for some time, and it appears to be pretty solid.

As far as I know, the SQLite databases are the preferred distribution method for WOF data going forward.

What is left before we consider setting `whosonfirst.sqlite` to true by default?

### LINKED ISSUE #469: Do not import both `whosonfirst-data-latest.db` and `whosonfirst-data-admin-$$-latest.db`
From this page it seems that https://dist.whosonfirst.org/sqlite/ `whosonfirst-data-latest.db` hasn't been updated since May while many `whosonfirst-data-admin-$$-latest.db` have been updated several times.

Is there some information within `whosonfirst-data-latest.db` that is not within all of `whosonfirst-data-admin-$$-latest.db`?

From https://github.com/whosonfirst-data/whosonfirst-data repository README: 
> Disclaimer
> As of May 2019, the whosonfirst-data repository has split into per-country repositories. You can read more about that change here. While we still track all issues in this repository, the data itself will live in the per-country repositories for the foreseeable future.
> 
> Per-country repositories have the following repository naming convention:
> 
> whosonfirst-data-admin-{2-char country code}

With `pelias/docker` and for the whole planet using `sqlite: true` the scripts imports both data-latest and the various data-admin per country (using inventory.json).

This seems to cause an issue for Switzerland for instance: many layers have been fixed recently (localities/localadmin https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/pull/4), since the importation order of the file is:
* `whosonfirst-data-admin-$$-latest.db` (includes the fix)
* `whosonfirst-data-latest.db`. (older records, don't include the fix)

The old records are replacing the updated ones since they mostly share the same whosonfirst ids.

Related: https://github.com/pelias/whosonfirst/issues/437
Also probably related: https://github.com/pelias/pelias/issues/811

Best,
Cyprien

### PR DESCRIPTION
**Pull request by Joxit**
BREAKING CHANGE: drop support for wof bundles
BREAKING CHANGE: `imports.whosonfirst.sqlite` default to `true`

## Background

WOF database is hosted on [geocode.earth](https://geocode.earth/data/whosonfirst), both per country and global admin are available, I'm updating the default endpoint in favor of geocode.earth.

## What's new ?

A new config is available `config.imports.whosonfirst.countries`. This configuration take care advantage of the per country databases, it will allow you to download only the wanted countries. If the config is not present, it will download the global databases.

Minor fix introduced by #483 `bunzip2` and not `bunzip`

## Discussion

1. ~~In this PR, I did only the SQLite part, the bundle download is not compatible with geocode.earth. The old way was per placetype, now it's admin/postalcode/constituency. That's means old users with a custom download URL will have some issues.~~ **Breaking change**
2. ~~`importPlaces` are very useful for small imports, now the per country is available, should we deprecate it ?~~ Or **use both `countries` and `importPlaces`** ?
3. ~~`importPlaces` extract data in bundle format, should we deprecate this part to ?~~ **Deprecated**
    - Pros:
      - Code less complicated
      - Easier to maintain (SQLite everywhere)
    - Cons:
      - Bundle format can be faster than SQLite at runtime...
4. Should we remove the support of venue ?

related: pelias/whosonfirst#460 pelias/whosonfirst#469 pelias/whosonfirst#477 pelias/wof-admin-lookup#289

Fixes #469
Closes #460
Fixes #437

### CODE REVIEW

**Comment by missinglink** [comment]
FYI we don't currently build venue data, I could add that but I assumed it was old, unmaintained and noone was using it?

**Comment by Joxit** [comment]
I agree with you. I also think that nobody uses venue :man_shrugging:.
I added venue in the white-list just in case.

Edit discussion: Should we remove venue ?

**Comment by missinglink** [comment]
Actually Julian and I discussed it on a call today.

I think WOF venues are 'soft deprecated', our experience with them is that the data old and hasn't had new contributions for a long time.

As such we (Geocode Earth) will not be publishing dist files for WOF venues, the official dist.whosonfirst.org downloads are probably as up-to-date as they will ever be.

Regarding Pelias, it seems a pity to delete code which supports WOF venues since other developers may benefit from it, but if it becomes a maintenance burden then it may be ok to do so.

**Comment by missinglink** [comment]
So... Maybe we just have a generic warning message that the file you requested isn't available on the host you specified and leave it at that for now?

**Comment by missinglink** [comment]
If we want to be very thorough we could grab inventory files from both hosts and compare the last_modified time to find the best download.

But maybe this is overkill? But it would allow 'fallback' to dist.whosonfirst.org for files not published by GE

**Comment by Joxit** [comment]
> Regarding Pelias, it seems a pity to delete code which supports WOF venues since other developers may benefit from it, but if it becomes a maintenance burden then it may be ok to do so.

You are right... So, if and only if venue are activated, we can add download it from WOF ? Maybe I have an elegant way to do this :thinking: I will try it tomorrow :)

> Maybe this is overkill? But it would allow 'fallback' to dist.whosonfirst.org for files not published by GE

Yes this is overkill :sweat_smile: 

Since we want to promote SQLite over Bundles, we can migrate to data GE only SQLite download part ? With some deprecation warnings ?

**Comment by Joxit** [comment]
Updated, I added the backward compatibility for venues via WOF

**Comment by missinglink** [comment]
Nice, I just checked on the build and it's finished, just syncing the files to the bucket, so it should be available shortly.

**Comment by orangejulius** [comment]
Cool, I'm currently testing this out (actually, on top of the minor fix in #484). It seems to work well so far but unfortunately we don't have a lot of automated testing around the download functionality :( :(

I think if we are going to merge this and default to Geocode Earth's WOF data (which I fully support), then we need to do one of two things:

- Change the code in this repo to download `whosonfirst-data-admin-latest.db` by default instead of `whosonfirst-data-latest.db`
- Ensure our Geocode Earth data builds copy `whosonfirst-data-admin-latest.db` to `whosonfirst-data-latest.db`

The first of these would mean that we lose compatibility with the data on `dist.whosonfirst.org`, but it means we wouldn't have to add yet another backwards-compatibility complexity to the WOF build scripts. I understand they've already gotten quite complicated and it's actually really very hard to reliably and automatically build all the WOF data we need on a regular basis.

**Comment by orangejulius** [comment]
Also, I extracted the bugfix for the `bunzip2` command into #488, so eventually we can rebase this against master and keep the changes in this PR limited to just what's needed :)

**Comment by Joxit** [comment]
With this PR, by default it will download `whosonfirst-data-admin-latest.db` from Geocode Earth. But this will fail if the source is something like WOF... They do not provide `whosonfirst-data-admin-latest.db`... Only per country extracts so this PR will break old builds :slightly_frowning_face:

What can we do ? Download all `whosonfirst-data-(admin|postalcode|venue)-{country}-latest` or `whosonfirst-data-latest.db` when a custom source is used ?

I have already sync the PR :wink:

**Comment by Joxit** [comment]
New commit to be compatible with WOF for full planet download

**Comment by orangejulius** [comment]
Hi! Big news today!

Who's on First has turned off their downloads at [dist.whosonfirst.org](https://dist.whosonfirst.org).
Screenshot_2020-04-17_10-55-54

I haven't been following recent changes to the WOF importer _super_ closely, but that really simplifies things for this PR, doesn't it? There's now no need at all to worry about backwards compatibility with `dist.whosonfirst.org`.

**Comment by Joxit** [comment]
Oh! That's interesting ! 

Yes, this simplify a little bit the PR, but there are still users using custom URLs :disappointed:.
One question remains, what is the future of venues ?

**Comment by missinglink** [comment]
We have no plans to publish venues distributions at this time.

I call a vote to remove supports for WOF venues in order to simplify the code.

:+1: for yes :-1: for needs further discussion

**Comment by pixeldublu** [comment]
This should be pushed forward. Wof just disabled their downloads. But the changes from the pr are not enough. The structure from https://geocode.earth/ is different and lots of things are not working anymore...

**Comment by Joxit** [comment]
Hi @pixeldublu I started this PR in March and the WOF change was made last Friday.

This PR was originally made for SQLite download only. Are you using SQLite or bundle download ? Why this PR is not working for you ?

**Comment by pixeldublu** [comment]
For example venues are not available anymore... and i the bundles also not available anymore...

**Comment by Joxit** [comment]
Yes, check out our discussion here https://github.com/pelias/whosonfirst/pull/487#issuecomment-616404444
We are planning to remove the support of venues... Venues are not really updated by WOF team and seems to be outdated... That's why we want to remove this support.

If you need further discussion, fell free :slightly_smiling_face: 

The bundle was out of the scope of this PR. I will add it later.

**Comment by pixeldublu** [comment]
I was trying to make individual db downloads last week and then this wof download disable happened :)

So i made some changes to my PR to use geocode earth and works but its not mergeable yet. Looking for improvement ideas.

**Comment by Joxit** [comment]
Big commit.... BREAKING CHANGE is coming !

I dropped the support for bundle, the `importPlaces` download case is no longer useful thanks to per country download, so I removed this code too.
I removed unused dependencies.
schema update: sqlite default to true !

**Comment by orangejulius** [comment]
Oh, `importPlace` is still quite useful, if you can keep it. It allows areas smaller than a country to be imported, reducing the number of records that aren't relevant for a specific use case.

**Comment by Joxit** [comment]
Only the download part has be deleted (download of the 40Go SQLites + generating bundle like architecture).

The `importPlace` feature is always be present for import and pip-service. Now, instead of generating bundle like architecture, we will load only interesting documents with this piece of code from #417: 

https://github.com/pelias/whosonfirst/blob/d7f5b51d8804dd0d4ece601fa922ced544eda8cd/src/components/sqliteStream.js#L73-L91

That means it will work like a charm even for small areas :slightly_smiling_face: 

For example, I want only `Ile-de-France` macroregion, the config will be:

```json
{
  "datapath": "/opt/whosonfirst/",
  "importPostalcodes": true,
  "countries": "fr",
  "importPlace": 404227465,
  "sqlite": true
}
```

Inport time is 2 secondes and the last log is:
```
2020-04-21T22:42:31.990Z - info: [dbclient-whosonfirst]  paused=false, transient=0, current_length=0, indexed=5009, batch_ok=11, batch_retries=0, failed_records=0, localadmin=1277, country=1, macroregion=1, region=8, macrocounty=24, county=249, locality=1982, borough=20, macrohood=4, neighbourhood=914, postalcode=529, persec=500.9
```

Full France import time is 1min16s and the last log is:
```
2020-04-21T20:24:16.887Z - info: [dbclient-whosonfirst]  paused=false, transient=0, current_length=0, indexed=109398, batch_ok=219, batch_retries=0, failed_records=0, country=1, dependency=4, disputed=2, macroregion=13, region=101, macrocounty=328, county=3232, localadmin=35291, persec=889.8, locality=58987, borough=45, macrohood=4, neighbourhood=5336, postalcode=6054
```

**Comment by orangejulius** [comment]
Oh, duh, right! Import place is no longer needed at download time :)

I just tested it out and I think it works great. Thanks for taking care of this super fast! :speedboat:

Anything left or should we hit merge?

**Comment by Joxit** [comment]
`importVenues`, `missingFilesAreFatal` and `importIntersections` are still present in the schema. Should I remove them ?

https://github.com/pelias/whosonfirst/blob/d7f5b51d8804dd0d4ece601fa922ced544eda8cd/schema.js#L17-L34

`sqlite` is set to true, at import time, if this is not true I throw an exception, it's ok ?

https://github.com/pelias/whosonfirst/blob/d7f5b51d8804dd0d4ece601fa922ced544eda8cd/src/readStream.js#L52-L54

**Comment by missinglink** [comment]
Yes, I think if the code is not going to be able to support a configuration value then it should fail loudly and with a good message so that users know how to fix their config.

Not sure if I brought this up before but the new variable in `whosonfirst` is called `countries` whereas the one in `geonames` is called `countryCode`. It's really not a big deal (and I don't really care that they are different) but I thought I'd mention it 🤷

**Comment by missinglink** [comment]
Sorry for the nit pick but can we please change the error message to 'Bundles are no longer supported!'

**Comment by missinglink** [comment]
I've never been so pleased to see so many deletions ;)

There are still some `venue` specific code (and regex patterns) in `utils/download_sqlite_all.js`, can we remove these?

**Comment by missinglink** [comment]
Regarding the `admin-xy` repo that we talked about in the past, on reflection, I think this isn't strictly required for most installations as it includes `planet` `continent` `timezone` and `empire` records which the majority of users probably don't want in their index anyway?

There are definitely other placetypes in there but it's probably not worth forcing users to download `admin-xy`?

```
sqlite> SELECT placetype, COUNT(*) AS count FROM spr GROUP BY placetype ORDER BY placetype;
placetype|count
campus|13826
continent|8
county|34
empire|12
localadmin|1
locality|2033
marinearea|305
neighbourhood|1945
ocean|7
planet|1
region|23
timezone|376
```

**Comment by missinglink** [comment]
Can we also drop support for WOF `intersections`?

I don't recall anyone ever using that feature and the data is static, we have ways of generating intersection datasets from OSM for those who require something similar and I think it'll be more suitable.

**Comment by Joxit** [comment]
Hey ! New commit !
- I renamed `countries` to `countryCode`
- Fix wording 
- I plan to delete useless options, but we must make the changes in `pelias-config` first (tests are failing)

I feel that the intersections were already filtered :thinking:

**Comment by missinglink** [comment]
:tada:

**Comment by Joxit** [comment]
Well done everyone :smile: :rocket:

**Comment by orangejulius** [comment]
Well done mostly to you @Joxit for doing most of the work to start this PR and the one in Placeholder :)

I just had some fun adding `countryCode` to all our Docker projects and the fast, small downloads are so nice! :tada: 

If there are any bugs they probably came in from all my rebasing, let us know :)

**Pull request merged**
