### PR TITLE
Fix placetype order

### PR DESCRIPTION
**Pull request by orangejulius**
I somehow messed up the order when working on https://github.com/pelias/whosonfirst/pull/119.
Since `county` records were being loaded and processed before
`macrocounty` records, its possible that some records were missing the
`macrocounty` hierarchy elements.

### CODE REVIEW

**Comment by missinglink** [comment]
:shipit:

**Comment by dianashk** [comment]
LGTM

**Comment by trescube** [comment]
:shipit:

**Comment by orangejulius** [comment]
Wow the mythical 3x code review!

**Pull request merged**
